plugins {
    id 'com.android.library'
    id 'kotlin-android'
}

android {
    compileSdk= 36

    defaultConfig {
        minSdkVersion 23
        targetSdkVersion 36
        versionCode 1
        versionName "2.8.1"
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    namespace 'com.github.barteksc.pdfviewer'
}

dependencies {
    implementation 'androidx.core:core-ktx:1.17.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation("io.github.oothp:pdfium-android:1.9.5-beta01")
}